### PR TITLE
Asthma study (Han et al. 2020)

### PR DESCRIPTION
**Pull request by sinarueeger**
Han et al. 2020 (https://doi.org/10.1038/s41467-020-15649-3) - multi-ancestry study.

image

## Data origin 

[Table S3](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-15649-3/MediaObjects/41467_2020_15649_MOESM2_ESM.pdf) is used for `J10_ASTHMA_multi.csv` (_Results for 167 loci significantly associated with asthma in GWAS meta-analysis of the UK Biobank and TAGC._)

[Table S5](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-15649-3/MediaObjects/41467_2020_15649_MOESM2_ESM.pdf) is used for `J10_ASTHMA.csv` (_Association results for 66 previously unknown loci and 3 additional loci when only subjects of European  ancestry from TAGC were included in the meta-analysis._)

## Problems

- `rs755023315` has no position (https://www.ncbi.nlm.nih.gov/snp/?term=rs755023315).
- Both tables report no `beta` or `se`, only Z and P. The full summary stats sent by Hooman Allayee (hallayee@usc.edu) is for the multi-ancestry meta-analysis only, so could technically be used for `J10_ASTHMA_multi.csv` used for novelty reporting.

### CODE REVIEW

**Comment by Lipastomies** [comment]
GWAS Catalog [claims](https://www.ebi.ac.uk/gwas/variants/rs755023315) rs755023315 has been merged to rs1555764957. Seems it was in dbsnp build 151 but not in current build (154): https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?do_not_redirect&rs=rs755023315

**Comment by sinarueeger** [comment]
In the orignal table S5 it says: 
image

The classic dbSNP view says: 
image

I propose to set the position to 6579018

**Comment by Lipastomies** [comment]
We don't seem to have it in FG summary stats (there's chr19_6579018_GC_G/rs56725395, but it doesn't seem to be the same variant), so we can't really compare it against FinnGen. My opinion would be that unless it's super duper important for some reason, we leave it out.

**Comment by sinarueeger** [comment]
Thanks @Lipastomies.

I removed all sumstats of `rs755023315` and added a note (for trackability).

**Pull request closed without merging**
