### PR TITLE
Update Skin Cancer

### PR DESCRIPTION
**Pull request by sinarueeger**
Update for Melanoma (36,760 cases, incl. proxy cases) with Landi et al. (2020) (10.1038/s41588-020-0611-8). 
- This is an update for melanoma study from Ransohoff (2017) (10.18632/oncotarget.15230). 
- There was little overlap with oncotarget, so just added new lines for each variant.
- Table used: https://www.nature.com/articles/s41588-020-0611-8/tables/2

## Note
I can spot that some digits were removed from beta column, must be working with google sheet. I could fix that.

### CODE REVIEW

**Comment by Fedja** [comment]
Actually the proxy cases are not good for beta matching! For identifying novelty yes. Can you have separate stats with and without proxy

**Comment by sinarueeger** [comment]
@Lipastomies can you add `C3_SKIN_EXALLC_proxy.csv` to the match file gs://misc-analysis/betamatch_ext_data/github_match_file_r4.tsv? (I can do that too, but don't want to infer with your pipeline).

**Comment by Lipastomies** [comment]
@sinarueeger done

**Comment by sinarueeger** [comment]
## Betamatching results

For `C3_SKIN_EXALLC_PROXY`
image
 and for `C3_SKIN_EXALLC`(unchanged)
image

Two variants that had no FinnGen entry: 
```
  `#chrom`      pos
1        3 69964940
2       12 17122526
```

Four variants have non-matching effect size signs: 
```
 `#chrom`       pos alt_ext ref_ext unif_beta_ext unif_beta_fg
1        1  63261871 T       C              0.151       -0.0501
2        9 107949305 C       G              0.0953      -0.009 
3        9 131582193 G       A              0.0619      -0.006 
4       12 116142486 G       A              0.0943      -0.008 
```
I looked up all those four again in Table 2 of the paper and in results.finngen.fi : they indeed have the effect size direction that they have.

**Pull request closed without merging**
