### PR TITLE
Fixing POAG loci from previous study

### PR DESCRIPTION
**Pull request by sinarueeger**
When updating the POAG loci, I noticed that the previously listed POAG loci from Choquet et al. (https://www.nature.com/articles/s41467-018-04555-4) only listed the GERA top hits. 

However, the manuscript has two parts: GERA, UKBB, and meta-analysis of the two. 

I removed the GERA hits only and added GERA+UKBB meta-analysis results (contains the GERA hits). 

- GERA (discovery): 4 986 POAG cases from 4 race/ethnicity groups (non-Hispanic whites, Hispanic/Latinos, East Asians, and African-Americans)
- UKBB: 7 329 glaucoma cases and 169 561 controls from five race/ethnicity groups (European, East Asian, South Asian, African British, and mixed ancestries)
- Found in [Supp Table 8](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-04555-4/MediaObjects/41467_2018_4555_MOESM2_ESM.pdf
): Lead SNPs (P < 5 x 10-8) in the multiethnic meta-analysis (GERA+UKB)

### CODE REVIEW

**Comment by sinarueeger** [comment]
> Missing column names for gene and rsid

Fixed

**Comment by Fedja** [comment]
looking good

**Comment by sinarueeger** [comment]
@Lipastomies is this one ok now?

**Comment by sinarueeger** [comment]
## Betamatching
Looks like lots of allele swaps

image

## sign not matching
```
  X.chrom       pos alt_ext ref_ext   beta_ext alt_fg ref_fg beta_fg unif_alt unif_ref
1       7  73907881      TG       T -0.3566749      T     TG -0.0100        A       AC
2       9 104933567       A       G  0.1484200      A      G -0.2017        A        G
3      17  10127866       G       A  0.1739533      G      A -0.1784        G        A
  unif_beta_ext unif_beta_fg
1     0.3566749      -0.0100
2     0.1484200      -0.2017
3     0.1739533      -0.1784
```

## no FinnGen match
```
  `#chrom`       pos alt_ext ref_ext
     <dbl>     <dbl> <chr>   <chr>  
1        2 152448216 A       C  

```

**Comment by sinarueeger** [comment]
Turns out, Supp Table 8 only had the META analysis discovery variants, and not the ones from Table 2 and 3. So now I only added table 2 (est from GERA) and 3 (est from UKBB) and a note saying from which cohort they are. Estimates are pretty consistent though. 
image

**Comment by sinarueeger** [comment]
## Betamatching

image

`rs149154973` has different effect size direction, but only SNP in GERA (table 2) that did not appear in UKBB. 
```
         rsid X.chrom      pos alt_ext ref_ext   beta_ext alt_fg ref_fg beta_fg unif_alt unif_ref
1 rs149154973       7 73907881      TG       T -0.3566749      T     TG   -0.01        A       AC
  unif_beta_ext unif_beta_fg
1     0.3566749        -0.01

```

`rs56117902` not in FinnGen. 

## GERA vs. UKBB
Regarding Table 2 (Gera) and Table 3 (UKBB) comparison: looks like GERA is a slightly better match, but has 1 variant with non matching effect size direction. 
image

**Pull request closed without merging**
